### ISSUE TITLE
#181 2 electric boogaloo

### ISSUE THREAD

**Issue by deltanedas** [FabricMC/fabric#1347] opened 2021-03-06 17:36 UTC
With Minecraft 1.16.5, Fabric Loader 0.11.1, Fabric API 0.30.3+1.16 I cannot connect to BungeeCord servers (tried cubecraft.net).

After encrypting, I am disconnected with the error being
```
[Netty Epoll Client IO #0/WARN]: Received invalid channel identifier "BungeeCord" from connection net.minecraft.class_2535@2e55d77f
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:BungeeCord
```

#181 is back

**Comment by deltanedas** [comment] 2021-03-06 21:37
only appears when hydrogen is used.

**Comment by modmuss50** [comment] 2021-03-06 21:45
I was unable to reproduce this with just fabric installed. It does log a warning to the console, but I was able to plan on cubecraft just fine.

**Comment by Technici4n** [comment] 2021-03-06 22:28
Closing this as it doesn't seem to be a fabric API issue after all.

**Closed as completed by Technici4n** 2021-03-06 22:28 UTC
Labels: bug, module: networking api
