### ISSUE TITLE
Item group modifications affect the inventory item group

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric#2603] opened 2022-10-22 21:17 UTC
```java
ItemGroupEvents.MODIFY_ENTRIES_ALL.register((group, entries) -> {
    entries.addAfter(Items.HOPPER, OAK_HOPPER);
});
```

<img width="368" alt="image" src="https://user-images.githubusercontent.com/24855774/197362781-67054816-bc29-415b-8eee-d1de37dad25e.png">

**Comment by modmuss50** [comment] 2022-10-22 21:32
I can see the use case of wanting to add after only when an existing item exists, so I think something needs to be done to accomodate this better.

One idea I had would be to add some methods to allow querying if an item existis.

So this would become something like:

```java
if (entries.contains(Items.HOPPER))
   entries.addAfter(Items.HOPPER, OAK_HOPPER);
```

Another option would be to add an `addAfterExisting` but I think the above would be more verstile.

**Comment by modmuss50** [comment] 2022-11-10 09:54
Please retest once 22w45a is out as I cannot reproduce this.

**Comment by modmuss50** [comment] 2022-11-13 14:45
Fixed with https://github.com/FabricMC/fabric/pull/2653

**Closed as completed by modmuss50** 2022-11-13 14:45 UTC
