### ISSUE TITLE
replaces items

### ISSUE THREAD

**Issue by jSdCool** [FabricMC/fabric#464] opened 2019-12-16 21:58 UTC
when i booted up my server i found that my fireworks were pumpkin pies, my eleytra was a sheld and my blast furnace was a smoker and all mob heads were wither skull

in addition all item frames were glitched

luckily this is all temporary and by reverting to vanilla it fixes its self

**Comment by modmuss50** [comment] 2019-12-16 22:01
Was this with a vanilla client?

**Comment by jSdCool** [comment] 2019-12-20 19:44
Yes

**Comment by Dinip** [comment] 2019-12-22 15:00
same issue here, have a fabric server with carpet and need fabric-api to load Fabric-Discord Link. people with the vanilla clients have items changed, like said before (fireworks are pies, elytra is a shield). for people with fabric clients, everything is fine

**Comment by liach** [comment] 2019-12-23 03:37
Does this happen with only fabric (loader) without fabric registry sync?

**Comment by Dinip** [comment] 2019-12-23 12:31
ok, seems that I needed to delete `/world/data/fabricRegistry.dat`. the server was running 1.14.4 fabric+fabricAPI+carpet+FBLink and when I updated it to 1.15 I only deleted the .fabric folder. 
now it is running fine with fabricAPI
[Found this issue later yesterday](https://github.com/FabricMC/fabric/issues/458)

**Comment by modmuss50** [comment] 2019-12-23 12:35
I think the issue is when updating vanilla worlds from 1.14 to 1.15 fabric isnt following vanillas registry.

Im not sure, but my guess is vanilla is shifting the ids around and fixing them via a datafixer.

Sloving this has a few challanges, as it should ensure that all vanilla ids are kept the same, but then ensure that they do not conflict with added mods when updating the world.

**Comment by jSdCool** [comment] 2019-12-23 14:24
Could you provide a step by step prosees for fixing this?

**Comment by Dinip** [comment] 2019-12-23 14:28
@jSdCool if you are updating from 1.14.4 to 1.15.1 you need to delete two folders
- .fabric in your server root folder 
- ./world/data/fabricRegistry.dat (this fixed my problem)
edit: make sure that you have a backup just in case :)

**Comment by jSdCool** [comment] 2019-12-23 15:05
hmm now it just fills the console with errors and doesn't continue to load

**Comment by i509VCB** [comment] 2020-03-10 05:30
Could you link a log with the errors?

**Comment by Prospector** [comment] 2020-05-14 17:23
Duplicate of #122

**Closed as completed by Prospector** 2020-05-14 17:23 UTC
Labels: bug, module: registry sync
