### ISSUE TITLE
Crash on start version 0.5.2.40 1.15.2

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#631] opened 2020-05-22 06:17 UTC
When I don't have any mods in my mods folder Fabric will start normally. But, when I put in Fabric API and Doors of Infinity it gives this crash report:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 5/22/20 2:13 AM
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'doorsofinfinity'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:392)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: com/qouteall/immersive_portals/render/PortalEntityRenderer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.qouteall.immersive_portals.render.PortalEntityRenderer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:392)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 931750136 bytes (888 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 2.0.1
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 2.13.2
		doorsofinfinity: Doors of Infinity 1.0.7
		fabric: Fabric API 0.10.8+build.310-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.1.0+3e5587510c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.8.4+build.198
		minecraft: Minecraft 1.15.2
	Launched Version: fabric-loader-0.8.4+build.198-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by i509VCB** [comment] 2020-05-28 03:11
~~The cause seems to be immersive portals. Have you tried launching the game without it?~~

Edit: It seems you don't have immersive portals installed, have you installed it?

> Caused by: java.lang.ClassNotFoundException: com.qouteall.immersive_portals.render.PortalEntityRenderer

**Comment by ghost** [comment] 2020-05-28 03:22
Yes, that issue is actually resolved now. But while trying to get my mods together, I've run into another issue. I should also mention that I'm getting this error from failing to start a Minecraft server, rather than my client.

[23:14:59] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'compact-storage'
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:228) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
        at net.minecraft.class_3176.<init>(class_3176.java:100) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:941) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2618
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at me.tobystrong.compactstorage.CompactStorage.<clinit>(CompactStorage.java:57) ~[compact-storage-fabric-4.0.3-1.15.2.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
        ... 20 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2618
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at me.tobystrong.compactstorage.CompactStorage.<clinit>(CompactStorage.java:57) ~[compact-storage-fabric-4.0.3-1.15.2.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_241]
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
        ... 20 more

I've seen a couple solutions. I've read that I should delete the config folder for the mod and let it replace itself, but this mod doesn't have a config folder. I've also deleted and reinstalled the server files, didn't work. I've also tried running the server with Compact Storage and the Fabric API alone (without all my other mods) and it's given me the same error message.

So, you mind helping me on this one?

**Comment by i509VCB** [comment] 2020-05-28 03:27
> Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2618

Which is `ChestAnimationProgress` This is a special case since you have to tell loader to only implement it on the client using:
```java
@EnvironmentInterfaces(@EnvironmentInterface(
    value = EnvType.CLIENT,
    itf = ChestAnimationProgress.class
))
```
This is because it is a client only interface.

So it's a mod issue, which you should contact the author about

**Comment by ghost** [comment] 2020-05-28 03:29
Oh, ok then. I guess I'll go do that. But thanks for the help though!

**Comment by i509VCB** [comment] 2020-05-28 03:29
Closing since this is an issue with a mod

**Closed as completed by i509VCB** 2020-05-28 03:29 UTC
Labels: status: waiting for feedback
