### ISSUE TITLE
Fabric API 1.20.6 breaks intentionally desyncronized custom recipes

### ISSUE THREAD

**Issue by kikugie** [FabricMC/fabric#3766] opened 2024-05-12 08:42 UTC
My mod creates instances of `SpecialCraftingRecipe` to manipulate the item components, but doesn't introduce any new items. To make the mod not require client side installation, I have a [mixin](https://github.com/kikugie/elytra-trims/blob/d264b50fd342e6c26b5c4cb733dc73268b29b7f5/src/main/java/dev/kikugie/elytratrims/mixin/common/SynchronizeRecipesS2CPacketMixin.java#L46) into `SynchronizeRecipesS2CPacket` to exclude my custom recipes from the registry sync. This works as expected - my custom recipes don't show up in the recipe book, but still can be crafted by players without the mod.

That is until Fabric API 0.98. [Use knownPackInfo on mod data packs to avoid registry syncing](https://github.com/FabricMC/fabric/commit/c0e5481f61aa0c28fc656f99c4da367278029a10) broke this behavior - recipe serializers are synchronized anyway and don't allow clients to join. Using Fabric API 0.97 or a fully vanilla client doesn't have this issue.

**Comment by apple502j** [comment] 2024-05-12 10:27
@kikugie This is weird, as that commit should only affect DRMs.

@jacobsjo Any opinions? @modmuss50 Maybe we should revert that change for .6?

**Comment by modmuss50** [comment] 2024-05-12 10:43
Im not going to rush to revert it, its still marked as a beta. 

I need to look at the code to be 100% sure, but I dont think it does only affect DRM though. I could be wrong. I think we need to understand the problem in detail before figuring out what to do next.

@kikugie can you provide a log or even a minimal reproduction example to help us understand the issue better?

**Comment by jacobsjo** [comment] 2024-05-12 12:11
I have no idea how the `knownPackInfo` could any effect on the RecipeManager. Its only used in `SynchronizeRegistriesTask`, which only deals with synced dynamic registries, i.e. using the `DynamicRegistriesS2CPacket`.

**Comment by kikugie** [comment] 2024-05-12 12:47
Sorry for the confusion, it seems like any fabric api release on 1.20.5+

## Error log:
https://mclo.gs/ETAzinz (Ik the namespace shouldn't be `minecraft`, I fixed it in the mod and it produces the same error)

## Steps to reproduce:
Server:
1. Create a 1.20.6 local fabric server
2. Install [Elytra Trims](https://modrinth.com/mod/elytra-trims/version/3.1.4)
3. Install [Fabric Language Kotlin](https://modrinth.com/mod/fabric-language-kotlin/version/1.10.20+kotlin.1.9.24)
2. Install [Fabric API](https://modrinth.com/mod/fabric-api/version/0.98.0+1.20.6)
3. Launch the server

Client (FAPI)
1. Create a 1.20.6 fabric instance
2. Install [Fabric API](https://modrinth.com/mod/fabric-api/version/0.98.0+1.20.6)
3. Join `localhost` server
4. *Crash linked above*

Client (no FAPI)
1. Create a 1.20.6 vanilla/empty fabric instance
3. Join `localhost` server
4. No error is printed in the log, recipes work

**Comment by apple502j** [comment] 2024-05-12 12:54
Intentional desynchronization has never been supported - especially in 1.20.5, as almost every registry-related entry is synced using integer IDs. Closing as wontfix.

**Closed as not planned by apple502j** 2024-05-12 12:54 UTC

**Comment by apple502j** [comment] 2024-05-12 12:56
If there is a good use for this, maybe FAPI could add a special case, otherwise I do not see any good solution just for this. also see #2168

**Comment by kikugie** [comment] 2024-05-12 13:23
What is the right way to achieve this behavior then?

**Comment by apple502j** [comment] 2024-05-12 13:45
@kikugie In an ideal world Fabric API would offer a way to register certain stuff at the very end of the registry. However that still leaves one question: how should we handle such entries within networking? There are many pitfalls, especially since 1) another mod could sync the recipe using raw ID, 2) that probably requires per-user raw ID rewriting on server side (which is too complicated), and 3) the expected behavior is undefined in many cases.

I recommend you consult with people familiar with the field of server-side only modding, like Patbox.
