### ISSUE TITLE
Support subfolders within the `mods` folder

### ISSUE THREAD

**Issue by RaptaG** [FabricMC/fabric#2309] opened 2022-06-11 13:19 UTC
When you create a folder inside the `mods` folder and try to place mods inside, after the game launches, these mods don't run. My opinion is that subfolders would be very useful when it comes to organization. For example, you would be able to separate a modpack's mods from user installed mods or even 2 or more modpacks which are installed in the same instance.

**Comment by Player3324** [comment] 2022-06-11 13:36
This is deliberate since there are quite a few false assumptions around subfolder semantics. You can add the jvm arg `-Dfabric.addMods=mods` to get the recursive behavior.

**Comment by haykam821** [comment] 2022-06-11 15:32
Duplicate of FabricMC/fabric-loader#81

**Closed as not planned** 2022-06-11 16:02 UTC
