### ISSUE TITLE
fabric-api-0.14.0+build.317-1.15.jar seems to be crashing 1.15.2 for some players.

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric#852] opened 2020-06-28 18:05 UTC
fabric-api-0.14.0+build.317-1.15.jar seems to be crashing 1.15.2 for some players.

reverting to fabric-api-0.13.1+build.316-1.15.jar seems to fix the problem.

---
https://discord.com/channels/507304429255393322/507982463449169932/726282959388147785

Anyone having an issue With Fabric API 0.14.0 - Build 317 for 1.15 on Fabric Loader version 0.8.8 build 202 for 1.15.2 where opening the Controls menu causes a crash? I do not have this issue with API 0.4.32 build 292 for 1.15.
https://pastebin.com/TvQu8hxh

---
https://discord.com/channels/507304429255393322/507982463449169932/726853859535749180

hi guys. when using fabric [1.15.2] Fabric API 0.14.0 build 317. On multiplayer it seems fine but in single player it crashes
hers my paste bin
https://pastebin.com/FAYVLX0T
just though id say
but when using [1.15.2] Fabric API 0.13.1 build 316
it seems to be fine???

---
https://discord.com/channels/507304429255393322/507982463449169932/726796838551683145

I get the following error when trying to open ANY singleplayer world. https://pastebin.com/RnCYwrq5

---
https://discord.com/channels/507304429255393322/507982463449169932/726798440213774366

Still crashing. Multiplayer works fine though either way https://pastebin.com/m4Zi0KTK

**Comment by liach** [comment] 2020-06-28 18:09
So problem with 2f23104bdd45dd034f584a7bb7d26b1e9fd32b36 ?

**Comment by calloatti** [comment] 2020-06-28 18:23
I forgot one small detail: It works fine for me.

**Comment by i509VCB** [comment] 2020-06-28 18:41
Really the two crashes should be two seperate issues since they target different modules.

Do the lifecycle events ones (last two pastebins) work?

**Comment by Earthcomputer** [comment] 2020-06-28 18:50
The last two pastebins possibly caused by optifabric?

**Comment by calloatti** [comment] 2020-06-29 11:12
Maybe related?

https://www.reddit.com/r/fabricmc/comments/hh07zh/fabric_api_crashing_minecraft_when_opening/

**Comment by uiytt** [comment] 2020-08-26 23:39
Does this still happen with latest 1.15.2 fabric build (Without optifabric) ?

**Comment by i509VCB** [comment] 2020-10-14 06:31
Closing since this is an issue with optifabric overriding synthetic methods.

**Closed as completed by i509VCB** 2020-10-14 06:31 UTC
