### ISSUE TITLE
[1.18.1] Fabric API 0.45.0+1.18 causing black window

### ISSUE THREAD

**Issue by TheButterbrotMan** [FabricMC/fabric#1931] opened 2021-12-23 16:52 UTC
The new Fabric API update is causing a black window in my modpack, when i change back to Fabric API 0.44.0+1.18 all works like intended.

https://pastebin.com/MQWxYnJg
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by warjort** [comment] 2021-12-23 18:12
> [13:56:59] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "fabric:registry/sync"
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097156bytes where max allowed: 2097152
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.9) ~[?:?]
	at net.minecraft.nbt.NbtTagSizeTracker.add(NbtTagSizeTracker:21) ~[?:?]

This is probably related to this fix: https://github.com/FabricMC/fabric/pull/1923
i.e. synchronizing the block entities to the client has blown the limit on the packet size

**Comment by warjort** [comment] 2021-12-23 18:24
https://github.com/FabricMC/fabric/blob/9481101883ae4a7283e9a142683939808f751c15/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java#L78

This invocation which is in your error stacktrace. Just uses the default hard coded packet size.
I don't see a way to configure a larger buffer or a way to tell it to split the buffer into multiple smaller ones.

**Comment by warjort** [comment] 2021-12-23 18:38
There is this mod:
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric
But I can't find the source for it so I don't know if it fixes your exact problem (the error message is slightly different).
It fixes a more general minecraft "bug": https://bugs.mojang.com/browse/MC-185901

**Comment by TheButterbrotMan** [comment] 2021-12-23 19:02
It looks like this solved my problem, thank you! I will do test it a little bit, to confirm that it works.

**Comment by deirn** [comment] 2021-12-24 07:04
Duplicate of #410, #1923 makes it easier to exceed packet limit size.
There's an ongoing PR that attempts to fix this issue (#1853)

**Closed as completed by deirn** 2021-12-24 07:04 UTC
Labels: resolution: duplicate, module: registry sync
