### ISSUE TITLE
Setting ResourcePackActivationType.DEFAULT_ENABLED does not work properly

### ISSUE THREAD

**Issue by Sollace** [FabricMC/fabric#3489] opened 2023-12-29 16:27 UTC
Using, as an example, the code from Presence Footsteps (in the ClientModInitializer):
![image](https://github.com/FabricMC/fabric/assets/6429283/0b695fd3-801c-4911-a55e-2da8d45be3f8)

The resource pack appears to be created and added to the game correctly, but I've found that it is not added to the list of enabled packs when launching the game with the mod installed for the first time. Instead I have to tell the user to enable the pack manually, which is rather problematic since it means I have to field bug reports from users not realising they have to enable to pack for the mod to work.

**Comment by Sollace** [comment] 2024-01-01 09:26
https://github.com/Sollace/Presence-Footsteps/issues/263

**Comment by apple502j** [comment] 2024-01-07 04:03
Cannot reproduce. Closing.

**Closed as not planned by apple502j** 2024-01-07 04:03 UTC
