### ISSUE TITLE
Mismatching blocks when Fabric API is installed

### ISSUE THREAD

**Issue by ZolaKluke** [FabricMC/fabric#512] opened 2020-02-28 03:51 UTC
Note there is no other mods installed on the server at all apart from just having fabric api installed.

**Fabric server without API**
![image](https://user-images.githubusercontent.com/6497775/75508842-905ef780-5a39-11ea-9a8a-b84a8ef51dfd.png)
Log: 
[latest.log](https://github.com/FabricMC/fabric/files/4265194/latest.log)
**Fabric server with API**
![image](https://user-images.githubusercontent.com/6497775/75508899-c0a69600-5a39-11ea-99dd-6034886af666.png)
Log:
[latest.log](https://github.com/FabricMC/fabric/files/4265197/latest.log)

Edit: I realised I was using an outdated version of fabric api, so I updated to the latest version for 20w09a and the issue still occurs

**Comment by liach** [comment] 2020-02-28 03:57
See #507.

**Comment by ZolaKluke** [comment] 2020-02-28 03:58
Oh thank you soo much

**Comment by Prospector** [comment] 2020-05-14 17:25
Duplicate of #122

**Closed as completed by Prospector** 2020-05-14 17:25 UTC
Labels: bug, status: in progress
