### ISSUE TITLE
Server only loads builtin language file

### ISSUE THREAD

**Issue by immibis** [FabricMC/fabric#1189] opened 2020-11-29 19:04 UTC
net.minecraft.util.Language.create() specifically loads language strings from `assets/minecraft/lang/en_us.json`. On the client this gets replaced once the resource pack system is initialized. On the server, nope, this default one is all you get.

It would be good if the server would load the en_us language files from mods as well as vanilla.

**Comment by i509VCB** [comment] 2020-11-30 07:40
This is a duplicate of #1096

**Closed as completed** 2020-12-20 14:12 UTC
Labels: resolution: duplicate
