### ISSUE TITLE
I am getting this crash/error while loading into a single player world.

### ISSUE THREAD

**Issue by VikranthMallru** [FabricMC/fabric#1529] opened 2021-06-28 15:36 UTC
I am getting this error while loading into a single player world. The world loads till 100% then crashes the whole game.
PS: the txt file for crash report.
 EDIT: i sent the wrong file, here is the correct one :
[crash-2021-06-28_20.54.19-client.txt](https://github.com/FabricMC/fabric/files/6730709/crash-2021-06-28_20.54.19-client.txt)

**Comment by silask7188** [comment] 2021-06-28 18:19
try removing optifabric+optifine(if you have it)

**Comment by VikranthMallru** [comment] 2021-06-29 03:02
I dont have an mods/ optifine/ optifabric running.

**Comment by frqnny** [comment] 2021-06-29 03:19
This is literally Forge crash report. What the heck.

**Comment by VikranthMallru** [comment] 2021-06-29 04:31
I have no idea what to do now, i can confirm that i was tryna run fabric, but it just crashes when i try to get into a single player world and it just crashes at 100%.

**Comment by frqnny** [comment] 2021-06-29 04:36
Well the log you gave us has optifine running. So you have fabric set up wrong or you gave us the wrong log

**Comment by VikranthMallru** [comment] 2021-06-29 04:40
Oh yeaa, I apologise for sending the wrong file, the attached file is the correct one.
[crash-2021-06-28_20.54.19-client.txt](https://github.com/FabricMC/fabric/files/6730683/crash-2021-06-28_20.54.19-client.txt)

**Comment by VikranthMallru** [comment] 2021-06-29 04:58
> Well the log you gave us has optifine running. So you have fabric set up wrong or you gave us the wrong log

[crash-2021-06-28_20.54.19-client.txt](https://github.com/FabricMC/fabric/files/6730751/crash-2021-06-28_20.54.19-client.txt)
The correct file is this.

**Comment by frqnny** [comment] 2021-06-29 13:15
Interesting. Must be a FRAPI rendering crash, can anyone who knows rendering try to explain what happened? He's just using FAPI and that's it.

**Comment by VikranthMallru** [comment] 2021-06-29 13:26
Uh, so what do i do now? pls help.

**Comment by Technici4n** [comment] 2021-06-29 13:41
Duplicate of #1479

**Closed as completed by Technici4n** 2021-06-29 13:41 UTC
