### ISSUE TITLE
Block Loot Tables Broken

### ISSUE THREAD

**Issue by Shnupbups** [FabricMC/fabric#214] opened 2019-05-26 07:31 UTC
I've gotten a few reports of Extra Pieces, along with other mods (namely Epicurean Gastronomy, Cotton Resources and Blockus) having their block drop loot tables broken (as in, none of the mods' blocks drop anything when mined) in recent versions of Fabric API (on 1.14.2).

Reportedly this affects API 0.3.0-pre builds 165, 166 and 167.

**Comment by InsomniaKitten** [comment] 2019-05-26 07:33
Duplicate of #210

**Closed** 2019-05-26 14:04 UTC
