### ISSUE TITLE
crash with fabric api 175 loading world(mouseClicked event handler at net.minecraft.class_437)

### ISSUE THREAD

**Issue by SDUBZ** [FabricMC/fabric#233] opened 2019-06-01 14:07 UTC
fabric loader: 1.14.2 build 2
crash report: http://puu.sh/DAd1U/9b08cb8563.txt

**Comment by shedaniel** [comment] 2019-06-01 14:12
Duplicate of #231?

**Comment by Boundarybreaker** [comment] 2019-06-01 15:50
yeah looks to be a dupe

**Comment by Prospector** [comment] 2019-06-03 01:51
Duplicate of #231

**Closed by Prospector** 2019-06-03 01:51 UTC
Labels: duplicate
