### ISSUE TITLE
[Indigo] Quad transforms can't change the RenderMaterial

### ISSUE THREAD

**Issue by Micalobia** [FabricMC/fabric#1766] opened 2021-10-09 19:00 UTC
So I'm having a weird issue where materials don't get applied in `QuadTransform`s

I know the transform is working because I do other things in my real code, it's just the material that does nothing

Simplified code here
```java
RenderMaterial material = ...
BakedModel model = ...
FabricBakedModel fmodel = model
QuadEmitter emitter = context.getEmitter();

// This works to change the material
for (BakedQuad quad : model.getQuads(...)) {
  emitter.fromVanilla(quad, material, ...)
  emitter.emit();
}

// This doesn't
context.pushTransform((quad) -> {
  quad.material(material);
  return true;
});
fmodel.emitBlockQuads(...)
context.popTransform()
```

I asked about it in the Fabric discord [here](https://canary.discord.com/channels/507304429255393322/807617488313516032/896458452925304922), and I couldn't find an explanation other than "It's probably an Indigo bug", which was supported by the bug not appearing with Canvas installed.

**Comment by Technici4n** [comment] 2022-12-21 11:19
Closing as a duplicate of #2639 which explains the cause of the issue. Working on the fix as we speak.

**Closed as completed by Technici4n** 2022-12-21 11:19 UTC
Labels: module: renderer indigo
