### ISSUE TITLE
Render issues with updated 1.15 worlds (vanilla)

### ISSUE THREAD

**Issue by MatthewOverall** [FabricMC/fabric#458] opened 2019-12-10 18:45 UTC
**Description**: Experiencing a dsync issue while including the latest fabric-api mod.

**Effect**: Items are rendered on the client incorrectly, (i.e Ghasts swapped for foxes, Elytras are rendered as shields, etc...)

**Workaround**: The workaround described by @modmuss50 is to delete the following files (please take a backup first)
- `/.fabric/` directory
- `/world/data/fabricRegistry.dat`

**Comment by liach** [comment] 2019-12-10 18:59
Hmm, so only deleting `.fabric` doesn't work? That part is loader-centric. The registry dat deletion is a fabric registry issue then.

**Comment by JamiesWhiteShirt** [comment] 2019-12-10 19:04
Is this happening when connecting to a remote server, or does it happen in single player?

**Comment by modmuss50** [comment] 2019-12-10 19:12
I think the way to reproude this is:

create a 1.14.4 server with only fabric-api
update that server and world to 1.15

While connecting with a vanilla client.

**Comment by creeper123123321** [comment] 2019-12-10 19:17
Maybe related with #135

**Comment by flori-schwa** [comment] 2019-12-11 14:41
I also had a similar issue but with blocks while updating my fabric server from 1.14.4 to 1.15 (mods: carpet and carpet-extra). Using a vanilla client, Blocks such as Smokers and blast furnaces did not render or rendered as other blocks such as lower spruce doors (and redstone dust once).

![](https://i.imgur.com/Vrc4Xbg.png)

**Comment by Prospector** [comment] 2020-05-14 17:23
Duplicate of #122

**Closed as completed by Prospector** 2020-05-14 17:23 UTC
Labels: bug, module: registry sync
