### ISSUE TITLE
Error starting dev server with 0.40.1 and mojang mappings

### ISSUE THREAD

**Issue by warjort** [FabricMC/fabric#1725] opened 2021-09-16 09:15 UTC
Log showing NPE during mixin remapping for gametest api:
[latest.log](https://github.com/FabricMC/fabric/files/7176421/latest.log)

Steps to reproduce:
* Checkout fabric example mod
* Change it to use fabric api 0.40.1
* Change it to use mojang mappings
* Type ````gradlew runserver````

Diff of changes described above (warning mojang mappings - but its just adding an s to a package name :-)
[diff.txt](https://github.com/FabricMC/fabric/files/7176464/diff.txt)

I don't know whether this is caused by an error in the new fabric gametest api or the update to mixins?
It works fine with yarn mappings.

Workaround, exclude the gametest api in your build:
````
    modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}") {
      exclude group: "net.fabricmc.fabric-api", module: "fabric-gametest-api-v1"
    }
````

**Comment by modmuss50** [comment] 2021-09-16 09:26
What loom version are you using?

**Comment by warjort** [comment] 2021-09-16 09:30
````
$ ./gradlew runserver
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

> Configure project :
Fabric Loom: 0.9.52
````

**Comment by modmuss50** [comment] 2021-09-16 10:09
Closing as this is a duplicate of #1722 👍

**Closed as completed by modmuss50** 2021-09-16 10:09 UTC
