### ISSUE TITLE
[22w11a] Fresh client install crashes on start-up

### ISSUE THREAD

**Issue by kwpugh** [FabricMC/fabric#2084] opened 2022-03-18 22:12 UTC
Log: https://gist.github.com/kwpugh/7360c1e6cbfd344cffa4167542d02847

Not sure if  this is Fabric or MultiMC 

MultiMC launches 22w11a fine without  Fabric API jar

**Comment by deirn** [comment] 2022-03-18 22:48
Duplicate of #2080, already fixed in #2081.

**Closed as completed by deirn** 2022-03-18 22:48 UTC
Labels: resolution: duplicate
