### ISSUE TITLE
Fabric API Renders Flowers as Centered On Block

### ISSUE THREAD

**Issue by Graywaren** [FabricMC/fabric#481] opened 2019-12-27 17:39 UTC
Hello
Fabric API is rendering flowers centered on their block as opposed to the offset that is normal in minecraft. I've looked, but I can't find any config options to turn this off or any other way to control it, and as fabric api is required for fabric mods, I can't remove it either. If I just missed the config for it, let me know.

I realize this may be intended behavior, but if so, can you please add a config for those of us who don't want flowers in a straight line? It'd be neat if there was any way to do it in a way that would let people who want to grow gardens in a straight line still be able to, while flowers on grass are still offset. Maybe by block types? Not sure if that's possible though. 

Anyway, really want a way to turn this off. 

Using minecraft 1.15.1 & fabric api 0.425+build.282

**Comment by coderbot16** [comment] 2019-12-27 17:46
Will be fixed by https://github.com/FabricMC/fabric/pull/480

**Comment by Juuxel** [comment] 2019-12-27 17:48
This is also a duplicate of #467.

**Comment by Graywaren** [comment] 2019-12-27 18:40
Sorry for the dupe! I searched for an open issue but only searched for flower terms, so didn't catch it. Thanks for letting me know! I think it would be cool if it was configurable. Thanks again, really glad to have fabric for all the client side mods it lets me have on the vanilla server I play on. =D

**Closed as completed** 2019-12-27 21:22 UTC
Labels: resolution: duplicate
