### ISSUE TITLE
when I update Fabric api and open a previously created world it says "errors in currently selected datapacks prevented the world from loading"

### ISSUE THREAD

**Issue by RynetheGrynd** [FabricMC/fabric#3277] opened 2023-08-23 01:48 UTC
I created my survival world in 1.19.2 with fabric api 0.59.0 and the auto created datapack from fabric api (not in datapacks folder). I tried updating the fabric api mod to 0.76.1 (latest for 1.19.2) and when I tried opening the world it shows that error message.

steps to recreate (not sure if it works, just what I did)
1. create world in 1.19.2 with fabric api 0.59.0.
2. replace fabric api with 0.76.1 for 1.19.2
3. open the world from step 1

I'm pretty sure it's an issue with the 0.59.0 datapack being incompatible with the new mod version and shows the error. I'm trying to download sodium extras and it requires 0.76.0. I can't delete the old datapack bc it's not in the datapacks folder.
![image_2023-08-22_204832762](https://github.com/FabricMC/fabric/assets/120495144/697dac72-d510-4d25-8c9a-909d8d895186)

**Comment by apple502j** [comment] 2023-08-23 02:47
Please attach the log files, found in the logs folder under `.minecraft`.

**Comment by RynetheGrynd** [comment] 2023-08-23 12:51
[latest.log](https://github.com/FabricMC/fabric/files/12419313/latest.log)

**Comment by apple502j** [comment] 2023-08-23 14:34
Not a bug on this side, so closing. Does seem like a mod incompatibility issue. Make sure to update all mods and try again.

**Closed as not planned by apple502j** 2023-08-23 14:34 UTC
