### ISSUE TITLE
Crash at the world creation screen with datapack content added through the Biome API

### ISSUE THREAD

**Issue by Hugman76** [FabricMC/fabric#2259] opened 2022-05-26 19:31 UTC
The game crashes when trying to create a world, if a mod with datapack content that is added through the Biome API is installed.
As a clear example, Promenade features Nether and End biomes and features that are now added by the mod's datapack (see commit https://github.com/DawnTeamMC/Promenade/commit/0e14663a8093a43ce420ed3f0958c8d13bbca925 and this [crash log](https://bytebin.lucko.me/SVmrvc6iGj)) and then added to vanilla generation through the Biome API, which is part of the Fabric API.

In vanilla Minecraft, when you try to create a world, the vanilla builtin worldgen gets loaded, and then opens the screen with the loaded generic content. However the Biome API lets us add to the vanilla generation by adding `RegistryKey`s, but actually requires these keys to represent built-in content so that it gets loaded on this specific screen. This constraint should not exist, and as a fix the Fabric API must tell the game to load the mod datapacks at the same time as builtin Minecraft worldgen content on this screen.

**Comment by apple502j** [comment] 2022-05-27 06:44
yet another duplicate of #2225

**Comment by Hugman76** [comment] 2022-05-27 08:27
This is not the same issue at all? You can load existing worlds, and the mod datapacks will work just fine. The issue is the create world screen.
Also, this is an issue I encountered on 1.18.2.

**Comment by apple502j** [comment] 2022-05-27 09:55
@Hugman76 This is the exact issue #2225 is describing. (Yes, it exists in 1.18.2 too, it should be renamed.)

If you could provide a minimum reproduction code, that'd be appreciated.

**Comment by Hugman76** [comment] 2022-06-02 13:55
This was not fixed.

**Comment by Hugman76** [comment] 2022-06-02 14:40
This issue was not fixed.

**Comment by Juuxel** [comment] 2022-06-02 14:54
It seems that the PR only fixed it for 1.19, but not 1.18.

**Comment by Hugman76** [comment] 2022-06-02 14:57
The issue is still present in 1.19 too

**Comment by Hugman76** [comment] 2022-06-02 15:14
Loading an existing world does not work either now, and sends to the "World is using experimental worldgen settings" screen when it tries to load, and still because it cannot find the values for the keys provided by the mod's datapack.
This still applies only if you use the Biome API.

**Closed as completed** 2022-06-13 19:08 UTC

**Comment by ghost** [comment] 2022-06-14 04:14
> It seems that the PR only fixed it for 1.19, but not 1.18.

Can someone confirm this?

**Comment by apple502j** [comment] 2022-06-14 08:26
Yeah, I have to backport the fix. There were quite a lot of changes there, which makes it not easy to do.

**Comment by apple502j** [comment] 2022-06-14 14:33
#2321 backports the fix.
