### ISSUE TITLE
Seems to change color saturation when loaded 

### ISSUE THREAD

**Issue by ni23237** [FabricMC/fabric#565] opened 2020-04-11 01:20 UTC
Attached are before and after pics. This is using the most recent version for the 20w15a minecraft snapshot. I'm not using any color altering programs like f.lux or anything.

![Before](https://user-images.githubusercontent.com/63482560/79032004-e4d8b500-7b57-11ea-97df-7f777a4b99e9.jpg)
![After](https://user-images.githubusercontent.com/63482560/79032006-e86c3c00-7b57-11ea-995e-c611a3a5099a.jpg)

**Comment by Prospector** [comment] 2020-04-14 05:48
Duplicate of #546

**Closed as completed by Prospector** 2020-04-14 05:48 UTC
Labels: resolution: duplicate
