### ISSUE TITLE
Neworking api crash

### ISSUE THREAD

**Issue by nullified33** [FabricMC/fabric#1337] opened 2021-02-26 22:00 UTC
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/26/21 1:58 PM
Description: Ticking memory connection

java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.<init>(CustomPayloadS2CPacket:43)
	at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:38)
	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:213)
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.createPacket(RegistrySyncManager.java:74)
	at net.minecraft.server.PlayerManager.handler$bjj000$onPlayerConnect(PlayerManager:2476)
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:184)
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:113)
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$dik000$handlePlayerJoin(ServerLoginNetworkHandler:562)
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:65)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:228)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at net.minecraft.server.MinecraftServer$$Lambda$9026/84530311.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1466492768 bytes (1398 MB) / 5603590144 bytes (5344 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Fabric Networking API (v1) (fabric-networking-api-v1), Fabric Registry Sync (v0) (fabric-registry-sync-v0)
	Fabric Mods: 
		adabraniummod: Adabranium 1.3.2+1.16.5
		adapaxels: AdaPaxels 1.0.6+1.16.5
		addendum: Addendum 1.16.5-1.0.2
		additionalbars: Additional Bars 1.0.1
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.7
		allure: Allure 1.2.8
		amecs: Amecs 1.3.3+mc.1.16.3
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		artifice: Artifice 0.14.6+1.16.5
		atbyw: All The Blocks You Want (ATBYW) 1.3.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bakingmod: Baking Mod 1.0.0
		beholdersvariations: Beholder's Variations 0.3.0
		betterend: Better End 0.9.1-pre
		betternether: Better Nether 5.0.7
		bigextras: Big Extras Mod 1.4
		biomemakeover: Biome Makeover 1.16.4-1.2.11
		bitsandchisels: BitsAndChisels 2.1.1
		blockus: Blockus 2.0.2+1.16.4
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.1.5
		cameraoverhaul: Camera Overhaul 1.0.1-fabric-1.16
		campanion: Campanion 1.3.4
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		celib: Celib - CebbyS Library Mod 0.3.1
		chainmail: Chainmail 0.5.0
		charm: Charm 2.2.2
		chiseldecor: Chisel Decor 1.1.2
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.10.13
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		columns: Columns 1.1.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_mouse0w0_fastreflection: FastReflection 1.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.1-1.16.4
		conjuring: Conjuring 0.1.3-beta
		connectiblechains: Connectible Chains 1.1.0
		continuebutton: Continue Button 1.0.2
		couplings: Couplings 1.3.3
		croptopia: Croptopia 1.2.0
		crumbs: Crumbs 1.0.6
		customportalapi: customportalapi 0.0.1-beta18-1.16
		darkpaintings: Dark Paintings 3.0.1
		dawn: Dawn API 1.6.5
		decorative: Decorative 4.0.0
		disco: disco 2.0.0
		dishes: Delicious Dishes 2.0.0
		earlygame: EarlyGame 1.16.x-1.1.1b
		earthtojavamobs: Earth2Java 1.6.1+1.16.4
		ecotones: Ecotones 0.7.1
		elevator: Elevator Mod 1.0.0
		emerald_tools: Emerald Tools 1.1.2
		expandedstorage: ExpandedStorage 5.6.32
		extra-discs: Extra Disks 1.0.1
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fabrictailor: Fabric Tailor 1.4.0-1.16.4
		fedora: Fedora 1.1.1-fabric-1.16.4
		fiber: fiber 0.23.0-2
		fluidphysics: Fluid Physics 1.4.0+fabric-1.16.4
		flytre_lib: FlytreLib 0.2.0
		funnel: Funnel 1.0.0
		glassential: Glassential 1.16.4-1.1.5
		gobber2: Gobber2 2.3.68
		hctm-base: HCTM Base 3.5.1
		here-be-no-dragons: Here be no Dragons! 1.0.0
		hplus: Better Hoppers (Hopper+) 2.1.0
		hydrogen: Hydrogen 0.2
		indium: Indium 1.0.0
		inmis: Inmis 2.1.1-1.16.4
		inventorypause: Inventory Pause 1.0.6
		invisframes: Invisible Frames 2.0.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kibe: Kibe 1.6.3-BETA
		lambdabettergrass: LambdaBetterGrass 1.0.3+1.16
		lepton: Lepton-Fabric 1.16.5-1.0.0
		libaddict: libaddict 0.2.1
		libblockattributes: LibBlockAttributes 0.8.6
		libblockattributes_core: LibBlockAttributes (Core) 0.8.6
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.6
		libblockattributes_items: LibBlockAttributes (Items) 0.8.6
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.2+1.16.4
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.3
		lonsdaleite: Lonsdaleite Tools 1.0.15
		ltr: LilTaterReloaded 1.1.10+1.16.3
		magna: Magna 1.4.2-1.16.2
		mealapi: Meal API 0.2+1.16.4
		megane: megane 3.1.3+1.16.5
		megane-api: megane-api 3.1.3+1.16.5
		megane-impl: megane-impl 3.1.3+1.16.5
		megane-runtime: megane-runtime 3.1.3+1.16.5
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		minegate-moreblocks: MineGate - MoreBlocks 1.1.1
		miniextras: Mini Extras Mod 1.2.1
		minimalmenu: MinimalMenu 1.16.5-0.0.5
		mocolors: Mo' Colors 1.0.1
		modern_beta: Modern Beta Fabric 1.0.7
		modmenu: Mod Menu 1.16.7
		more_gems: More Gems 1.1.22
		moreblocksmod: More Blocks Mod 0.1.4
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		mubble: Mubble 4.0-pre8
		mythicmetals: Mythic Metals 0.9.8
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		nmuk: No More Useless Keys 1.0.0+mc1.16.4
		nookbuild: NookBuild 1.4.0
		notenoughcrashes: Not Enough Crashes 3.1.5
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		originalblocks: OriginalBlocks 1.0
		oro_config: OroArmor Config 1.2.0
		overworld_two: Overworld 2 1.0.4
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.7.1+21w03a
		phosphor: Phosphor 0.7.1+build.11
		piglib: Piglib 1.0.0
		playerabilitylib: Pal 1.2.1
		programmerartinjector: Programmer Art Injector 1.2.1
		pugh_lib: Pugh Lib 1.1.0
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.8.1
		roughlyenoughitems: Roughly Enough Items 5.10.181
		roughlyenoughitems-api: REI (API) 5.10.181
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.181
		roughlyenoughitems-runtime: REI (Runtime) 5.10.181
		rswires: RSWires 4.10.2
		sandwichable: Sandwichable 1.2-beta5
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		secretrooms: Secret Rooms 0.9.3+1.16.5
		signretain: Sign Retain 1.0.3
		simpleplanes: simpleplanes 3.2.3
		skinnedlanterns: Skinned Lanterns 1.16.5-1.1.3
		slabref: Refabricated Slabs 0.3.1
		snm: Secrets No More 1.2.1
		sodium: Sodium 0.1.1-SNAPSHOT
		sodium-extra: Sodium Extra 0.2.0
		somnus: Somnus API 0.0.10-1.16.4
		spruceui: SpruceUI 2.0.4+1.16
		stacc: Stacc 1.0.1
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		sushimod: Sushi Mod 1.0.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.3.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		toms_storage: Tom's Simple Storage Mod 1.1.7
		traverse: Traverse 3.3.1
		trinket-heart-canisters: Trinket Heart Canisters 1.0.0
		trinkets: Trinkets 2.6.7
		unearthed: Unearthed 1.1.0
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanillaenhanced: VanillaEnhanced 1.4.0
		vanillaexcavators: Vanilla Excavators 1.1.0
		verticalredstone: Vertical Redstone 1.2.0
		vistas: Vistas 1.2.3
		voyager: Voyager 1.0.0
		white_rabbit: White Rabbit 1.0.7+21w03a
		wild_explorer: Wild Explorer 1.3.2
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		worldedit: WorldEdit 7.2.2+fc3c499
		wthit: wthit 2.2.1+1.16.5
		xlpackets: XLPackets 1.1
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods, slabref:pack, null, file/8_Silly_Minecraft_Features_Datapack.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 3

**Comment by nullified33** [comment] 2021-02-26 22:03
weird issue number

**Comment by modmuss50** [comment] 2021-02-26 22:25
This is happening becuase you have too many blocks/items/something in your registry. This a duplicate of: https://github.com/FabricMC/fabric/issues/410

**Closed as completed by modmuss50** 2021-02-26 22:25 UTC

**Comment by camilochys** [comment] 2021-07-14 08:19
So? Fix please? Thanks

**Comment by frqnny** [comment] 2021-07-14 12:00
there will be no fix the issue is closed

**Comment by nullified33** [comment] 2021-07-14 14:46
> This is happening becuase you have too many blocks/items/something in your registry. This a duplicate of: #410

how do you change the max packet/ registry size

**Comment by frqnny** [comment] 2021-07-14 14:56
XL Packets is one mod you could look to.

**Comment by nullified33** [comment] 2021-07-14 14:57
> XL Packets is one mod you could look to.

It's broken as far as i know

**Comment by frqnny** [comment] 2021-07-14 15:00
not really just report bugs to the mod author?
