### ISSUE TITLE
Blocks swapped

### ISSUE THREAD

**Issue by yentheo** [FabricMC/fabric#608] opened 2020-05-04 14:21 UTC
So I upgraded all the things to the 20w18a snapshot for as far as I know.
When I load up the game a lot of blocks are swapped with different blocks. E.g.
[How it should be](https://imgur.com/b7SAnU1)
[How it is](https://imgur.com/nX1ctrD])

I had this before and I think it solved itself by rebuilding and recopying or something, but I did everything 100 times from the start.

I can say that when I delete the mods folder but still load with the fabric loader, the world shows up fine. When I put in the mods (that I made myself,  build for the 20w18a api) which worked on 20w16a. 

This is my gradle properties file:
```
org.gradle.jvmargs  = -Xmx1G

#Fabric properties
minecraft_version   = 20w18a
yarn_mappings       = 20w18a+build.9
loader_version      = 0.8.2+build.194

#Mod properties
mod_version         = 0.0.0
maven_group         = one.spectra.minecraft.restream
archives_base_name  = spectra-restream

#Dependencies
fabric_api_version  = 0.10.3+build.338-1.16
```

When I start a clean world with the fabric loader installer, it seems to be working fine too.
Anybody knows what's up here?

**Comment by Prospector** [comment] 2020-05-04 18:41
When you upgrade the vanilla version, you need to delete the fabric registry files in your `world/data` folder. It's a bug where fabric-registry-sync doesn't keep the vanilla ids the same.

Duplicate of #464

**Closed as completed** 2020-05-04 18:42 UTC

**Comment by yentheo** [comment] 2020-05-05 04:12
@Prospector this was indeed the problem, thanks!
