### ISSUE TITLE
fabric-api-0.20.x mod resourcepack issue

### ISSUE THREAD

**Issue by nephatrine** [FabricMC/fabric#1065] opened 2020-09-06 19:38 UTC
I've got a custom resourcepack that overwrites textures from another mod (assets/appleskin/textures/icons.png). This resourcepack works fine using `fabric-api-0.19.0+build.398-1.16`, but updating to 0.20.0 or 0.20.1 causes the game to ignore the texture in my pack and use the mod's default texture instead. Vanilla textures overwritten in the same way work with either version, but the mod one does not.

**Comment by guestds** [comment] 2020-09-22 16:37
this seems to be related to the issue ive been having 

whenever i go to the resourcpacks and enable one, theres weird "ghost" resourcpacks enabled, if i check the options file, it has "file/*" for each proper pack, but on the right (the ones with raising priority) theres alot of fake packs referred to as "fabric/*" for each part of each mod and mod library 

if i enable a pack, i can still move it under the false packs, but theres nothing visual about where it it unless moving it around a proper pack

essentially its loading the mods as resourcepacks and giving the textures priority 

if i move every proper pack to higher priority, it does load files that alter mod textures

**Comment by ghost** [comment] 2020-09-26 06:31
It sounds like this is working as intended. All mods get loaded as resource/datapacks so that they can contain their own textures and data resources. The ghost resourcepacks you are seeing are likely just all of the mods being loaded. Just like all other texture packs it sounds like moving your custom texture pack to a higher priority will override the mod textures as intended.

**Comment by guestds** [comment] 2020-09-27 09:51
i dont think its intentional to have this in your options.txt file:
`resourcePacks:["fabric/autoconfig1u","fabric/cloth-config2","fabric/fabric","fabric/fabric-api-base","fabric/fabric-biome-api-v1","fabric/fabric-blockrenderlayer-v1","fabric/fabric-containers-v0","fabric/fabric-content-registries-v0","fabric/fabric-crash-report-info-v1","fabric/fabric-events-interaction-v0","fabric/fabric-events-lifecycle-v0","fabric/fabric-game-rule-api-v1","fabric/fabric-item-api-v1","fabric/fabric-item-groups-v0","fabric/fabric-key-binding-api-v1","fabric/fabric-keybindings-v0","fabric/fabric-lifecycle-events-v1","fabric/fabric-loot-tables-v1","fabric/fabric-mining-levels-v0","fabric/fabric-models-v0","fabric/fabric-networking-blockentity-v0","fabric/fabric-networking-v0","fabric/fabric-object-builder-api-v1","fabric/fabric-object-builders-v0","fabric/fabric-registry-sync-v0","fabric/fabric-renderer-api-v1","fabric/fabric-renderer-indigo","fabric/fabric-renderer-registries-v1","fabric/fabric-rendering-data-attachment-v1","fabric/fabric-rendering-fluids-v1","fabric/fabric-rendering-v0","fabric/fabric-rendering-v1","fabric/fabric-resource-loader-v0","fabric/fabric-screen-handler-api-v1","fabric/fabric-tag-extensions-v0","fabric/fabric-textures-v0","fabric/fabric-tool-attribute-api-v1","fabric/fabricloader","fabric/lightoverlay","fabric/mm","fabric/modmenu","fabric/mybrightness","fabric/okzoomer","fabric/optifabric","fabric/roughlyenoughitems","fabric/roughlyenoughitems-runtime","fabric/shulkerboxtooltip","fabric/voxelmap","fabric/waila","fabric/appleskin","vanilla","file/banner.zip","file/Clouds-Pack.zip","file/Milkyway Galaxy Day \u0026 Night.zip","file/FutureSpace_Addon+1.16.zip","file/Faithful-1.16.3.zip","file/FaithfulVenom-32x-1.15-r3.zip","file/1.15-r1.zip","file/VT Dark UI 1.16.zip","file/32x Outlined Ores Addon.zip","file/32x Tweaks.zip","file/FaithfulTweaks 1.16.3 V1.5.zip","file/FaithfulTweaks 1.16.3 AAA.zip","file/PureBDcraft Noteblock English MC113.zip","file/VT Quiter.zip","file/fonts.zip"]`

theres 65 files here, 50 are "fabric/", only 15 are "file/", 36 of these have "fabric/fabric"

**Comment by i509VCB** [comment] 2020-10-15 05:38
That seems to be the intended form in the options.txt file.

The many `fabric/fabric-...` are the individual modules of Fabric API. Nothing much we can really do about that without hardcoding special cases.

**Comment by guestds** [comment] 2020-10-15 15:41
i did a test, with the options.txt having all those above on that line, "fabric-api-0.19.0+build.398-1.16.jar" (as of now, latest 1.16.2 that isnt 20.x) had only 1 ghost pack, "fabric/fabric-tool-attribute-api-v1", and with roughly enough items and optifabric, neither get added as ghost packs, but something interesting, when i removed it and readded it (starting the game to let it update the file itself), the ghost pack seems to have only appears because in was in the list already, but doesnt add ghost packs in 19.x and doesnt remove them unless its not detected, again not readding it if it redetects it

it seems to be an unintended/unnoticed side effect of a change between 19.x and 20.x, still not fixed in "fabric-api-0.24.0+build.411-1.16.jar"

**Comment by Technici4n** [comment] 2022-06-01 08:36
Can someone reproduce this in modern versions (1.18.2 or 1.19)?

**Closed as not planned** 2022-06-07 12:57 UTC
Labels: bug, status: waiting for feedback
