### ISSUE TITLE
Using Loom 1.5 on multiloader crashes

### ISSUE THREAD

**Issue by CrypticVerse** [FabricMC/fabric#3556] opened 2024-01-28 21:26 UTC
Developing mod using:
Fabric API: 0.95.0+1.20.4
Fabric Loader: 0.15.3
Forge: 49.0.19
NeoForge: 20.4.83-beta

Log:

> Configure project :common
Targeting Minecraft '1.20.4' on a 'JOINED' platform

> Configure project :fabric
Fabric Loom: 1.5.7
Found existing cache lock file, rebuilding loom cache. This may have been caused by a failed or canceled build.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':fabric'.
> Failed to notify project evaluation listener.
   > Failed to setup Minecraft, java.lang.RuntimeException: Unexpected IllegalAccessException occurred (Gson 2.9.1). Certain ReflectionAccessFilter features require Java >= 9 to work correctly. If you are not using ReflectionAccessFilter, report this to the Gson maintainers.
   > Unexpected IllegalAccessException occurred (Gson 2.9.1). Certain ReflectionAccessFilter features require Java >= 9 to work correctly. If you are not using ReflectionAccessFilter, report this to the Gson maintainers.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 281ms

**Comment by CrypticVerse** [comment] 2024-01-28 21:27
This happens when trying to launch the fabric client

**Comment by modmuss50** [comment] 2024-01-28 21:41
This is a duplicate of: https://github.com/FabricMC/fabric-loom/issues/1020 and is a Gradle bug.

Make sure to update the foojay resolver plugin if you are using it, if not ensure that your plugin versons are specified in the root project.

**Closed as not planned by modmuss50** 2024-01-28 21:41 UTC
