### ISSUE TITLE
game won't launch

### ISSUE THREAD

**Issue by engi-gaming** [FabricMC/fabric#2064] opened 2022-03-11 02:01 UTC
whenever i try to launch fabric 1.18.2, this happens

Uncaught exception in thread "main"
java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.Logger com.mojang.logging.LogUtils.getLogger()' the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @604c5de8 of the current class, net/minecraft/client/main/Main, and the class loader 'app' for the method's defining class, com/mojang/logging/LogUtils, have different Class objects for the type org/slf4j/Logger used in the signature (net.minecraft.client.main.Main is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @604c5de8, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @5fe1ce85; com.mojang.logging.LogUtils is in unnamed module of loader 'app')
	at net.minecraft.client.main.Main.<clinit>(Main.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Linguardium** [comment] 2022-03-11 02:10
does this only occur with fabric loader13.3, fabric api 0.47.10+1.18.2 , and no other mods?

**Comment by warjort** [comment] 2022-03-11 10:41
Duplicate of https://github.com/FabricMC/fabric-loader/issues/622
If its not iris, it will be some other mod bundling sfl4j which is now "included" by minecraft itself as 1.18.2.

This is not a fabric api issue. If it were a fabric issue at all it belongs in the fabric-loader issues.
e.g. the fabric-loader could in principle exclude any slf4j classes from mod jars to avoid this problem

**Closed as completed** 2022-03-21 09:37 UTC
