### ISSUE TITLE
MultiMC FabricLoader 0.4.2-build.132 crash on start

### ISSUE THREAD

**Issue by LordRius** [FabricMC/fabric#156] opened 2019-04-26 13:19 UTC
Hi!

I'm writing a piece of code in eclipse and **debugging forks fine, no errors in console, no errors when compiling the code** but when i start MultiMC with Minecraft 1.14 instance and my mod, an error appears in console log and crash the game:

https://pastebin.com/0iXjZkH8

I'm using MultiMC with FabricLoader 0.4.2-build.132, mappings 1.14-build.1, using the same parameters in gradle.properties file... Also tried MultiMC with latest fabric loader and mappings version.

Any ideas?

Many thanks! and sorry for my english :p

**Comment by Madis0** [comment] 2019-04-26 15:34
Duplicate of #154

**Comment by AK9Official** [comment] 2019-04-26 15:35
@LordRius Was fixed in loader 0.4.4 build 137

**Comment by asiekierka** [comment] 2019-04-26 17:11
Fixed.

**Closed by asiekierka** 2019-04-26 17:11 UTC

**Comment by LordRius** [comment] 2019-04-28 10:49
Hi!

Sorry i just tried and i have the same error

https://pastebin.com/nVd2FcKH

Now i've MultiMC FabricLoader 0.4.4-build.137 and mappings 1.14-build.1. **Also tried with latest mappings and loader.**

Compiled modifying gradle properties loader version to 0.4.4-build.137... Any ideas?

Many thanks!

**Comment by asiekierka** [comment] 2019-04-28 11:25
Fabric API is missing. You can't use Fabric API classes without Fabric API - Loader is a separate thing.

**Comment by LordRius** [comment] 2019-04-28 12:09
Fixed now, many thanks asiekierka!
