### ISSUE TITLE
Possibility to add low-priority resource packs

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric#124] opened 2019-03-17 10:53 UTC
We should be able to add low-priority resource packs which we could use to change for example vanilla textures while still letting resource packs able to change them, it could be really useful for a lot of people

**Comment by ghost** [comment] 2020-10-21 04:28
Duplicate of #79 which also sounds like it was addressed by #1011.

**Closed by ghost** 2020-10-21 04:28 UTC
Labels: enhancement
