### ISSUE TITLE
Items displayed unnormally in 20w10a fabric server

### ISSUE THREAD

**Issue by Hibanaw** [FabricMC/fabric#514] opened 2020-03-05 03:11 UTC
The save was first created in 20w06a vanilla and can be used in the following snapshots and their fabric servers.
It's fine in 20w10a vanilla server but wrong in the fabric server.
The loader version is 0.7.8 build186 and the fabric api's version is 0.4.34 build.303
（sorry about my poor English）

**Comment by liach** [comment] 2020-03-05 03:15
See #507 and #512. So if you create a new world on the 20w10a fabric server, are things all right?

**Comment by Xuwznln** [comment] 2020-03-26 03:29
Same problem when updating from 20w12a to 20w13a along with update fabric api.
The client must be fabric in order to receive the correct items.
Also, I tried using vanilla client to open the map, there is no problem.

**Comment by liach** [comment] 2020-03-26 03:33
yes, apparently fabric registry sync doesn't know if data fixer has updated id and still loads registry info from old versions.

**Comment by Hibanaw** [comment] 2020-03-26 03:33
> Same problem when updating from 20w12a to 20w13a along with update fabric api.
> The client must be fabric in order to receive the correct items.
> Also, I tried using vanilla client to open the map, there is no problem.

The solution is
deleting the files named with "fabric" in world/data/

**Comment by Xuwznln** [comment] 2020-03-26 03:44
> The solution is
> deleting the files named with "fabric" in world/data/

oh, cool , I fixed the problem. Thanks

**Comment by Earthcomputer** [comment] 2020-03-26 07:52
Fabric registry sync should really ignore vanilla entries

**Comment by BlueSteelAUS** [comment] 2020-03-30 12:05
I just had the same problem upgrading my server from 20w12a to 20w13b .. everything appeared right on my client with the latest fabric and API installed. but not those using vanilla clients. 
as has been stated above i fixed the issue but removing the fabric*.* files from the world-save/data directory.   is there any way that this can be auto in future as this is a big gotcha. and some players don't like (or even know how to ) have to install fabric on their client. now that i know about it its easy enough for me to do. but for those that don't its a real head ache

**Comment by Prospector** [comment] 2020-05-14 17:26
Duplicate of #122

**Closed as completed by Prospector** 2020-05-14 17:26 UTC
Labels: question, module: registry sync, status: waiting for feedback
