### ISSUE TITLE
Invalid Player Data - Registry Overload

### ISSUE THREAD

**Issue by Bullseye55** [FabricMC/fabric#1835] opened 2021-11-16 07:14 UTC
https://github.com/AzureDoom/MCDoom/issues/19#issuecomment-969496931

As discussed in the discussion, a large modpack can overload Fabric's registry, causing "Invalid Player Data" errors.

**Comment by Technici4n** [comment] 2021-11-29 18:00
Duplicate of #410.

**Closed as completed by Technici4n** 2021-11-29 18:00 UTC
