### ISSUE TITLE
Fabric always fails with this

### ISSUE THREAD

**Issue by DivineSolar** [FabricMC/fabric#1315] opened 2021-02-14 06:05 UTC
Fabric is preparing JARs on first launch, this may take a few seconds...
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.nio.file.ReadOnlyFileSystemException
	at net.fabricmc.tinyremapper.TinyRemapper.waitForAll(TinyRemapper.java:917)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:742)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:706)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate(FabricLauncherBase.java:152)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:109)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 8 more
Caused by: java.util.concurrent.ExecutionException: java.nio.file.ReadOnlyFileSystemException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at net.fabricmc.tinyremapper.TinyRemapper.waitForAll(TinyRemapper.java:914)
	... 13 more
Caused by: java.nio.file.ReadOnlyFileSystemException
	at com.sun.nio.zipfs.ZipFileSystem.checkWritable(ZipFileSystem.java:155)
	at com.sun.nio.zipfs.ZipFileSystem.createDirectory(ZipFileSystem.java:416)
	at com.sun.nio.zipfs.ZipPath.createDirectory(ZipPath.java:634)
	at com.sun.nio.zipfs.ZipFileSystemProvider.createDirectory(ZipFileSystemProvider.java:201)
	at java.nio.file.Files.createDirectory(Unknown Source)
	at java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.nio.file.Files.createDirectories(Unknown Source)
	at net.fabricmc.tinyremapper.OutputConsumerPath.createParentDirs(OutputConsumerPath.java:336)
	at net.fabricmc.tinyremapper.OutputConsumerPath.accept(OutputConsumerPath.java:298)
	at net.fabricmc.tinyremapper.OutputConsumerPath.accept(OutputConsumerPath.java:50)
	at net.fabricmc.tinyremapper.TinyRemapper.lambda$apply$4(TinyRemapper.java:726)
	at net.fabricmc.tinyremapper.TinyRemapper.lambda$apply$5(TinyRemapper.java:739)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exiting with -1
Process exited with code -1.

**Comment by liach** [comment] 2021-02-14 09:02
Hmm, seems your game directory is within a zip. This is too cursed; fabric loader cannot output its mappings in this case and you need to use regular directories for your game directory. Looks like you are using OneSixLauncher, so if you don't have a clue you can ask them for help too.

**Comment by DivineSolar** [comment] 2021-02-14 17:09
I have tried a lot of things. I tried to use MultiMC and that's where this error is from. I just removed all minecraft files, reinstalled it and installed fabric again but all it does is close after launching and say an unexpected error has happened and the game has crashed. Exit code 0.

[12:08:34] [main/INFO]: Loading for game Minecraft 1.16.5
[12:08:34] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[12:08:34] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...

It looks like the remapped file each time is corrupt. Perhaps post yours?

**Comment by liach** [comment] 2021-02-14 17:24
Hmm, try delete the `.fabric` directory within your game directory, usually `%appdata%\.minecraft` on windows for vanilla launcher or it's set in your launcher

**Comment by DivineSolar** [comment] 2021-02-14 17:37
Alright, I have deleted it, launch?

**Comment by DivineSolar** [comment] 2021-02-14 17:42
I launched it once it crashes. Launched it a second time and get the same error

[12:41:42] [main/INFO]: Loading for game Minecraft 1.16.5
[12:41:42] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[12:41:42] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...

Deleting the fabric folder again.

**Comment by liach** [comment] 2021-02-14 17:49
If you continue to fail, consider getting the fabric installer from https://fabricmc.net/use (Java required to run) and install the latest fabric loader on 1.16.5

**Comment by DivineSolar** [comment] 2021-02-14 17:55
That what I used.

**Comment by liach** [comment] 2021-02-14 18:20
Can you try with vanilla launcher?

**Comment by DivineSolar** [comment] 2021-02-14 18:22
Yeah vanilla launcher launches just fine

**Comment by liach** [comment] 2021-02-14 18:26
Hmm, you might have to ask onesixlauncher for support

**Comment by DivineSolar** [comment] 2021-02-14 18:28
Onesixlauncher? Im not using that unless that's the fabric devs?

**Comment by liach** [comment] 2021-02-14 18:32
Yeah, i mean multimc

**Comment by DivineSolar** [comment] 2021-02-14 18:59
Right but I am just using the vanilla options atm.

**Comment by Chocohead** [comment] 2021-02-15 00:22
Are you running MultiMC from somewhere like Program Files where it might not have permission to create its own files?

**Comment by LorcanT** [comment] 2021-02-16 10:05
HI, I am actually having the exact same issue now. I created a new install of fabric for my new computer but I am having this issue on the regular Minecraft launcher.

[11:00:08] [main/INFO]: Loading for game Minecraft 1.16.5
[11:00:08] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
[11:00:08] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.nio.file.ReadOnlyFileSystemException
	at net.fabricmc.tinyremapper.TinyRemapper.waitForAll(TinyRemapper.java:917)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:742)
	at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:706)
	at net.fabricmc.loader.launch.common.FabricLauncherBase.deobfuscate(FabricLauncherBase.java:152)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at me.deftware.client.framework.main.Main.main(Main.java:43)
	... 8 more
Caused by: java.util.concurrent.ExecutionException: java.nio.file.ReadOnlyFileSystemException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at net.fabricmc.tinyremapper.TinyRemapper.waitForAll(TinyRemapper.java:914)
	... 14 more
Caused by: java.nio.file.ReadOnlyFileSystemException
	at com.sun.nio.zipfs.ZipFileSystem.checkWritable(ZipFileSystem.java:155)
	at com.sun.nio.zipfs.ZipFileSystem.createDirectory(ZipFileSystem.java:416)
	at com.sun.nio.zipfs.ZipPath.createDirectory(ZipPath.java:634)
	at com.sun.nio.zipfs.ZipFileSystemProvider.createDirectory(ZipFileSystemProvider.java:201)
	at java.nio.file.Files.createDirectory(Unknown Source)
	at java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
	at java.nio.file.Files.createDirectories(Unknown Source)
	at net.fabricmc.tinyremapper.OutputConsumerPath.createParentDirs(OutputConsumerPath.java:336)
	at net.fabricmc.tinyremapper.OutputConsumerPath.accept(OutputConsumerPath.java:298)
	at net.fabricmc.tinyremapper.OutputConsumerPath.accept(OutputConsumerPath.java:50)
	at net.fabricmc.tinyremapper.TinyRemapper.lambda$apply$4(TinyRemapper.java:726)
	at net.fabricmc.tinyremapper.TinyRemapper.lambda$apply$5(TinyRemapper.java:739)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exiting with -1
Process exited with code -1.

Booted up my old machine to see if it was broken there too but it seemed to launch fine there.

**Comment by liach** [comment] 2021-02-16 13:10
Are you on windows or mac? Do applications require special permissions to modify .minecraft folder on windows or minecraft on mac?

**Comment by LorcanT** [comment] 2021-02-16 13:39
> Are you on windows or mac? Do applications require special permissions to modify .minecraft folder on windows or minecraft on mac?

I am on Windows 10 and no none of my applications require special permissions.

**Comment by liach** [comment] 2021-02-16 15:26
that log above has 2 problems:
1. you are using multimc still
2. you are using deftware, which offers a patched fabric loader (usually for aristois hacked client).

try again using fabric installer and mojang's launcher

**Comment by LorcanT** [comment] 2021-02-16 16:37
> that log above has 2 problems:
> 
> 1. you are using multimc still
> 2. you are using deftware, which offers a patched fabric loader (usually for aristois hacked client).
> 
> try again using fabric installer and mojang's launcher

Okay so I just deleted my .minecraft folder and did a full restart! That seemed to have fixed the issue. Thanks for the help

**Comment by kb-1000** [comment] 2021-02-16 17:33
MultiMC works just fine with Fabric (it even includes an install button by itself. But do not attempt to use the installer with it). However, you're apparently using a hacked client, not Fabric. I assume you installed both? That won't work, uninstall the hacked client first.

**Comment by liach** [comment] 2021-02-16 17:52
Glad that things now work. Closing. For deftware there is no evidence that he is using aristois as only deftware appears, not aristois.

**Closed as completed by liach** 2021-02-16 17:52 UTC
Labels: question
