### ISSUE TITLE
Weird Crash on Startup 1.16.2

### ISSUE THREAD

**Issue by crdtrd** [FabricMC/fabric#1016] opened 2020-08-16 11:22 UTC
I'm having a crash on startup that happens whenever I have anything in the mods folder. It's not exclusive to Fabric API, but I'm hoping somebody could decrypt what's going on here for me. No crash report was created so I've just pasted the game output.

04:14:25.602
launcher
main
Preparing to launch minecraft client for fabric-loader-0.9.1+build.205-1.16.2
04:14:26.026
launcher
main
Checking installations.
04:14:26.027
launcher
main
Minecraft client fabric-loader-0.9.1+build.205-1.16.2 is ready to start.
04:14:26.027
launcher
main
Starting!
04:14:26.064
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
04:14:26.604
FabricLoader
main
Loading for game Minecraft 1.16.2
04:14:26.852
Fabric|Loader
main
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution failed!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:600)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:202)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:79)
	at net.fabricmc.loader.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:67)
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:452)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
04:14:26.890
launcher
main

04:14:26.890
monitor
Process Monitor
Process crashed with exit code 1

**Comment by ghost** [comment] 2020-08-16 12:09
This can have several causes...  Hard drive full, corrupted archives, wrong permissions, ...
Make sure there aren't any zip files anywhere but in the world's datapacks folders.

Can you give the filename, its size and source where to get it from, of a mod you want to put in the mods folders?

**Comment by crdtrd** [comment] 2020-08-17 06:43
None of my hard drives are full. However, I am running my Minecraft with my game directory on an external drive. I tried changing the game directory to a folder on my internal drive and it worked like a charm. Mods loaded correctly. No more crashes. Weird. This has never been a problem in the past for me but I guess it is now. 
I am on a Mac and I recently updated the OS to Catalina. I wonder if that has anything to do with it.
The reason why I've been running with the game directory on an external drive is simply to save space on the internal drive. The external drive is a 500GB Samsung T5, formatted with ExFAT (which I know isn't generally considered to be a very good format, but it's ability to be used by both Mac and Windows is valuable to me).

The mods I've tried using are fabric-api-0.18.0+build.397-1.16.jar (624 KB) and fabric-carpet-1.16.2-1.4.8+v200811.jar (1.1MB), each being the only mod in the mods folder. I get all my mods off of CurseForge.

**Comment by crdtrd** [comment] 2020-08-17 06:54
I also just tried on a different external drive that I have, a 1TB Sandisk Extreme that formatted with Mac OS Extended (Journaled). It worked. Must be something to do with the Samsung and ExFAT. I wonder if reformatting it would fix the problem.

**Comment by modmuss50** [comment] 2020-08-17 07:08
The format of the drive shouldnt matter?

**Comment by i509VCB** [comment] 2020-10-14 07:04
Closing since this does not seem to be an issue with Fabric API. This issue seems to occur with frequency so it is a duplicate of sorts.

**Closed as completed by i509VCB** 2020-10-14 07:04 UTC
Labels: status: waiting for feedback
