### ISSUE TITLE
Ticking Entity Crash on Player in relation to keybinds

### ISSUE THREAD

**Issue by Geneticus** [FabricMC/fabric#889] opened 2020-07-12 21:16 UTC
Submitting issue here per mod author request  Log file is attached to the link. https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/issues/76

**Comment by liach** [comment] 2020-07-12 21:28
`Caused by: java.lang.NoSuchMethodError: net.fabricmc.fabric.mixin.client.keybinding.KeyCodeAccessor.getBoundKey()Lnet/minecraft/class_3675$class_306;`

Looks like FabricMC/Mixin#28. 

Also note to author to use this hook https://github.com/FabricMC/fabric/blob/a35bc9fe9a0cef448ab418c624ccff808af91086/fabric-key-binding-api-v1/src/main/java/net/fabricmc/fabric/api/client/keybinding/v1/KeyBindingHelper.java#L55 instead of stuff in the `mixin` package in the future.

**Comment by Prospector** [comment] 2020-07-13 02:52
It's hard to tell what's going on here because this mod is not visible source.

**Comment by thexaero** [comment] 2020-07-15 16:05
@liach Thanks for the tip. Somehow missed that. Going to switch to it.
@Prospector I really doubt anything on my end will help. I was simply calling _((KeyCodeAccessor) keyBinding).getKeyCode()_ from _PlayerEntity.tick()_. Going to switch to _KeyBindingHelper.getBoundKeyOf_ but it does the same thing. 
EDIT: And I do make sure it's on the client side, btw, if it even matters.

**Comment by uiytt** [comment] 2020-08-26 23:58
@thexaero is this fixed since [this](https://github.com/FabricMC/Mixin/pull/33) was merged ?

**Comment by thexaero** [comment] 2020-08-27 07:28
@uiytt I haven't received any other crash reports like this, so probably. I don't know a way to reproduce this though.

**Comment by uiytt** [comment] 2020-08-27 07:43
Well, can someone close this, and if someone get again this error on the new version, you can re-open this thread.

**Comment by liach** [comment] 2020-08-27 14:55
don't think that's the related issue. it's that impl changed so mod using impl detail breaks.

**Closed as completed by liach** 2020-08-27 14:55 UTC
Labels: help wanted

**Comment by thexaero** [comment] 2020-08-27 15:16
@liach This was before _KeyCodeAccessor.getBoundKey()_ was renamed, if that's what you mean.
