### ISSUE TITLE
Mod Organization Support with Folders of Version for names

### ISSUE THREAD

**Issue by cowboy8625** [FabricMC/fabric#1123] opened 2020-10-17 12:23 UTC
In your `mods` folder I would like to be able to organize my mods I am using with folders of the version number that they should be used/loading in when *Fabric* loads as the name of the folder.

#### **Example**
```
mods -
          |-1.16.0 -| "fabric-api-0.24.0+build.411-1.16"
          |             | "litematica-fabric-1.16.0-0.0.0-dev.20200913.215807"
          |
          |-1.16.3 -| "fabric-api-0.24.0+build.411-1.16"
                        | "litematica-fabric-1.16.3-0.0.0-dev.20200913.215807"
```
![image](https://user-images.githubusercontent.com/43012445/96337014-461e9b00-1049-11eb-8785-d1565240f7c8.png)

**Comment by AMereBagatelle** [comment] 2020-10-17 12:28
You can use MultiMC to manage mod versions easily.  Also, this is the repository for fabric API (yeah, it's confusing).

**Comment by JamiesWhiteShirt** [comment] 2020-10-17 12:44
Duplicate of this issue on Fabric Loader: https://github.com/FabricMC/fabric-loader/issues/181

**Comment by modmuss50** [comment] 2020-10-17 14:48
Duplicate issue, even the vanilla launcher supports a way to safely seprate instances.

**Closed as completed by modmuss50** 2020-10-17 14:48 UTC

**Comment by cowboy8625** [comment] 2020-10-17 23:39
oh really!   I dislike MultiMC so that is not an Option.  I will look into how to use the launcher to support this.  I looked but I guess I missed #118 sorry for the confusion! Have a good one.
