### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by OMGNeedsHelp** [FabricMC/fabric#965] opened 2020-07-28 22:29 UTC
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ninjaphenix-container-lib'!

Help me!

**Comment by haykam821** [comment] 2020-07-28 22:31
This is not a place for issues caused by Fabric mods. You might want to join [the Discord guild](https://discord.gg/v6v4pMv) instead.

**Comment by OMGNeedsHelp** [comment] 2020-07-28 22:32
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/28/20 3:27 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ninjaphenix-container-lib'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.lambda$onRegister$1(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl$$Lambda$2391/1762494982.accept(Unknown Source)
		at java.util.Optional.ifPresent(Optional.java:159)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.onRegister(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.register(PacketRegistryImpl.java:66)
		at net.kyrptonaught.inventorysorter.InventorySortPacket.registerReceivePacket(InventorySortPacket.java:18)
		at net.kyrptonaught.inventorysorter.InventorySorterMod.onInitialize(InventorySorterMod.java:26)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2144/849256436.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 26 more
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.lambda$onRegister$1(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl$$Lambda$2391/1762494982.accept(Unknown Source)
		at java.util.Optional.ifPresent(Optional.java:159)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.onRegister(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.register(PacketRegistryImpl.java:66)
		at com.terraformersmc.campanion.Campanion.registerServerboundPackets(Campanion.java:85)
		at com.terraformersmc.campanion.Campanion.register(Campanion.java:69)
		at com.terraformersmc.campanion.Campanion.onInitialize(Campanion.java:47)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2144/849256436.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 27 more
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.lambda$onRegister$1(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl$$Lambda$2391/1762494982.accept(Unknown Source)
		at java.util.Optional.ifPresent(Optional.java:159)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.onRegister(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.register(PacketRegistryImpl.java:66)
		at com.qouteall.hiding_in_the_bushes.MyNetwork.init(MyNetwork.java:55)
		at com.qouteall.immersive_portals.ModMain.init(ModMain.java:89)
		at com.qouteall.hiding_in_the_bushes.ModEntry.onInitialize(ModEntry.java:13)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2144/849256436.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 27 more
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.lambda$onRegister$1(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl$$Lambda$2391/1762494982.accept(Unknown Source)
		at java.util.Optional.ifPresent(Optional.java:159)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.onRegister(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.register(PacketRegistryImpl.java:66)
		at spinnery.common.registry.NetworkRegistry.initialize(NetworkRegistry.java:175)
		at spinnery.Spinnery.onInitialize(Spinnery.java:22)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2144/849256436.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 26 more
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.lambda$onRegister$1(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl$$Lambda$2391/1762494982.accept(Unknown Source)
		at java.util.Optional.ifPresent(Optional.java:159)
		at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.onRegister(ServerSidePacketRegistryImpl.java:97)
		at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.register(PacketRegistryImpl.java:66)
		at me.shedaniel.rei.RoughlyEnoughItemsNetwork.lambda$null$5(RoughlyEnoughItemsNetwork.java:69)
		at me.shedaniel.rei.RoughlyEnoughItemsNetwork$$Lambda$2882/1425994440.run(Unknown Source)
		at me.shedaniel.math.api.Executor.run(Executor.java:15)
		at me.shedaniel.rei.RoughlyEnoughItemsNetwork.onInitialize(RoughlyEnoughItemsNetwork.java:67)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2144/849256436.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 28 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.lambda$onRegister$1(ServerSidePacketRegistryImpl.java:97)
	at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl$$Lambda$2391/1762494982.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.onRegister(ServerSidePacketRegistryImpl.java:97)
	at net.fabricmc.fabric.impl.networking.PacketRegistryImpl.register(PacketRegistryImpl.java:66)
	at ninjaphenix.containerlib.ContainerLibrary.onInitialize(ContainerLibrary.java:72)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2144/849256436.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayNetworkHandlerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 680110384 bytes (648 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.5.1
		adorn: Adorn 1.9.1+1.16.1
		adventurez: AdventureZ 1.0.6
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		artifice: Artifice 0.8.0+1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		betterdroppeditems: Better Dropped Items 1.2.1-1.16
		betternether: Better Nether 3.5.2
		blue_endless_jankson: jankson +
		campanion: Campanion 1.1.13+build.35
		cardinal-components-base: Cardinal Components API (base) 2.4.0
		cardinal-components-item: Cardinal Components API (items) 2.4.0
		cardinal-components-world: Cardinal Components API (worlds) 2.4.0-nightly.1.16-rc1.build.2
		chainmail: Chainmail 0.3.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		creativebuttonmover: Creative Button Mover 0.2.5
		crimsonmoon: Crimson Moon 1.1.0-1.16
		crusade: Crudade Mod 1.1.2
		dishes: Delicious Dishes 1.0.3
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		expandedstorage: ExpandedStorage 5.3.16
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		firstperson: FirstpersonModel 1.2.0
		gravestones: Gravestones 1.4.0
		immersive_portals: Immersive Portals 0.23
		inmis: Inmis 1.2.0-1.16.1
		inventorysorter: Inventory Sorter 1.7.0-1.16
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.0.4-1.16
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		lvmnt: SuperAxes 1.1.4
		magna: Magna 1.1.3-1.16.1
		minecraft: Minecraft 1.16.1
		mobz: MobZ 2.4.3
		modmenu: Mod Menu 1.14.5+build.30
		more_gems: More Gems 1.0.45
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		parchment: Parchment 1.0.2+1.15.2
		piglintag: PiglinTag 1.0.0
		raa_core: RAA: Core 0.1.7+1.16.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.3.2
		roughlyenoughitems: Roughly Enough Items 4.10.3
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		shapes: Shapes 2.0.0+build.10
		simpleteleporters: Simple Teleporters 2.2.0
		sodium: Sodium 0.1.0
		spinnery: Spinnery 3.1.12
		staffofbuilding: Staff of Building 1.2.0-1.16
		staticdata: Static Data 1.1.2
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		traverse: Traverse 2.2.14+build.28
		trees-do-not-float: Trees Do Not Float 1.10.90
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vampirelib: VampireLib 1.8.0+build.1-1.16.1
		vanilla-hammers: Vanilla Hammers 2.0.1-1.16.1
		wildworld: Wild World 1.2.3-1.16
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by OMGNeedsHelp** [comment] 2020-07-28 22:32
> This is not a place for issues caused by Fabric mods. You might want to join [the Discord guild](https://discord.gg/v6v4pMv) instead.

Its because of a mod?

**Comment by haykam821** [comment] 2020-07-28 22:36
This issue tracker is for issues relating to the Fabric API, not specific mods. Your issue should be on the specific mod's issue tracker.

**Comment by uiytt** [comment] 2020-08-27 00:32
Can someone close this please ? As this is related to some mods.

**Closed as completed** 2020-08-27 00:56 UTC
