### ISSUE TITLE
"Registry remapping failed!" with no discernible clue as to why

### ISSUE THREAD

**Issue by Skeithh** [FabricMC/fabric#1963] opened 2022-01-21 16:05 UTC
I'm genuinely at a loss right now. Last night, everyone could enter and leave my server with no problems. Nothing has changed between last night and now in terms of server configs, files, or anything on the client side for the players. Yet starting today my players have randomly been getting the "Registry remapping failed!" insta-boot. Sometimes it only happens on relog, sometimes it happens before even having logged in ONCE to the server. Doesn't matter if server was freshly restarted or has been running for a bit.
The server does not spit anything odd out that I can tell is a problem.

I've had them:

- Match the server's configs 1:1
- Reinstall fabric
- Restart PC

And none of these worked.

I attached the server log and one of their latest logs
[latest (14).log](https://github.com/FabricMC/fabric/files/7915018/latest.14.log)
[server latest log.txt](https://github.com/FabricMC/fabric/files/7915024/server.latest.log.txt)

I genuinely do not know what this can even be. Where this issue came from. How I can fix it or even prevent it. 

Fabric version: 0.12.12
Minecraft version 1.18.1

**Comment by deirn** [comment] 2022-01-21 16:31
```
[16:52:52] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:game_event contains IDs unknown to the receiver!
 - minecraft:death
 - minecraft:click
 ```

Did a quick search on GitHub, it seems that both of those are from "The Wild Mod".
https://github.com/Osmiooo/wildmod/blob/906022ece2038158d704f1559e72cfc8f8660032/src/main/java/frozenblock/wild/mod/fromAccurateSculk/ClickGameEvent.java#L9-L10

Are you sure you have the same version of mods installed on the server and the client? If so, can you send the full server log?

**Comment by Skeithh** [comment] 2022-01-21 16:53
At the moment I do not have the ability to pull the full log, but I will remove The wild mod and tell my players to try in the meantime. By the time that I can have the files pulled we will likely have come to the conclusion on if that was indeed the cause.

**Comment by warjort** [comment] 2022-01-21 16:53
My guess is this is a bug in "The Wild Mod".
Those new game events are registered in the static class initialiser of the  ````ClickGameEvent```` class.

But from what I can see, nothing actually forces that class to be loaded/initialised on the client when run in client/server mode.

Without those new events being registered the sync of the registry from the server will fail.

I would guess one way to workaround this problem (without a fix for the mod) 
would be go into a client world before accessing the server.
Make sure to spawn in and place a skulk sensor if the world doesn't already have one,
This will cause those registrations to happen because the class will now be loaded.

With the registrations now done you should be able to login to the server.

**Comment by Skeithh** [comment] 2022-01-21 16:58
I see, I'll test that and if that is a workaround I will ask my players if they'd prefer to just do the workaround or if we'd rather have it just be left out until it gets fixed.

**Comment by deirn** [comment] 2022-01-21 17:12
Closing this as it's not an issue with fabric itself.

**Closed as completed by deirn** 2022-01-21 17:12 UTC

**Comment by Xfrtrex** [comment] 2022-01-21 18:27
> My guess is this is a bug in "The Wild Mod". Those new game events are registered in the static class initialiser of the `ClickGameEvent` class.
> 
> But from what I can see, nothing actually forces that class to be loaded/initialised on the client when run in client/server mode.
> 
> Without those new events being registered the sync of the registry from the server will fail.
> 
> I would guess one way to workaround this problem (without a fix for the mod) would be go into a client world before accessing the server. Make sure to spawn in and place a skulk sensor if the world doesn't already have one, This will cause those registrations to happen because the class will now be loaded.
> 
> With the registrations now done you should be able to login to the server.

Hey! i work on the wild mod, i will share this with the team now.

**Comment by Xfrtrex** [comment] 2022-01-21 18:45
wait, what version of the mod are you using?

**Comment by AViewFromTheTop** [comment] 2022-01-21 20:51
> I'm genuinely at a loss right now. Last night, everyone could enter and leave my server with no problems. Nothing has changed between last night and now in terms of server configs, files, or anything on the client side for the players. Yet starting today my players have randomly been getting the "Registry remapping failed!" insta-boot. Sometimes it only happens on relog, sometimes it happens before even having logged in ONCE to the server. Doesn't matter if server was freshly restarted or has been running for a bit. The server does not spit anything odd out that I can tell is a problem.
> 
> I've had them:
> 
> * Match the server's configs 1:1
> * Reinstall fabric
> * Restart PC
> 
> And none of these worked.
> 
> I attached the server log and one of their latest logs [latest (14).log](https://github.com/FabricMC/fabric/files/7915018/latest.14.log) [server latest log.txt](https://github.com/FabricMC/fabric/files/7915024/server.latest.log.txt)
> 
> I genuinely do not know what this can even be. Where this issue came from. How I can fix it or even prevent it.
> 
> Fabric version: 0.12.12 Minecraft version 1.18.1

Hello! I'm also part of The Wild Mod Team, the person who was unfortunate enough to cause this issue.
Would you be able to test this version of the mod and let us know if it happens? https://github.com/Osmiooo/wildmod/actions/runs/1730701281
I would also appreciate a response being posted on https://github.com/Osmiooo/wildmod/issues/60 instead of here, as this isn't a Fabric issue and you haven't opened up an issue on our GitHub.
I never caught this issue because it simply doesn't occur with the original mod I'd ported the GameEvent/New Sculk stuff from, and even reproducing the exact steps, I can't find an issue with it. For some reason TWM seems to break my code at times, even though nothing should be causing that to happen... This sadly isn't the first time something like this has happened.
