### ISSUE TITLE
ATMF Developer finds bug that causes Server Files to not load and REI to takes ages to populate

### ISSUE THREAD

**Issue by furtabs** [FabricMC/fabric#1142] opened 2020-10-27 16:04 UTC
https://gist.github.com/tyrolanuthmatar/1a4217d507d1349ece21fe8cb9f27b56

Some mod is registering a super long NBT Value and causing REI to not load it but also the server crashes. Well it doesnt crash it just takes ages to populate REI. like 20 mins

**Comment by furtabs** [comment] 2020-10-27 16:10
@shedaniel wanted me to report here because it might be a fabric ovesight. Any clues to said mod will be gladly appreciated.

**Comment by haykam821** [comment] 2020-10-27 16:11
Partial duplicate of #410 

This is an issue with mods simply registering too many things to Fabric API-synced registries. Future compressions in the sync packet will deter this.

**Comment by i509VCB** [comment] 2020-10-27 17:37
Sadly we cannot just whip up a new registry sync compression system since that would have breaking changes for all connecting clients. There have been some ideas on how to handle it and the current solutions are pending the new networking api so we could do login stage registry sync.

**Comment by i509VCB** [comment] 2020-12-25 05:27
Closing since this is a duplicate of another issue.

**Closed as completed by i509VCB** 2020-12-25 05:27 UTC
Labels: resolution: duplicate, module: registry sync
