### ISSUE TITLE
nineBlockStorageRecipes doesn't save with mod id

### ISSUE THREAD

**Issue by supersimple33** [FabricMC/fabric#3270] opened 2023-08-17 03:58 UTC
If you call `CustomModRecipeProvider.nineBlockStorageRecipes` it will save the advancements it creates for recipe possession tracking with the wrong Mod id for the resource location ("minecraft:", instead of "custommod:"). While it is easy to work around this, it would be nice if fabric added functionality to allow the passing of a mod id to CustomModRecipeProvider.nineBlockStorageRecipes so that developers can each call the same function instead of having to reimplement a work around for each mod they work on. If this is something that may be added please let me know and I will draft a PR and if this is not wanted let me know and I will close this.

**Comment by Technici4n** [comment] 2023-08-17 09:04
Duplicate of #2962. If you can provide a fix for that issue go ahead!

**Closed as not planned by Technici4n** 2023-08-17 09:04 UTC
