### ISSUE TITLE
Failed to read accessWidener file from mod fabric-object-builder-api-v1 in 1.19 build 4

### ISSUE THREAD

**Issue by CodeCraftPlugin** [FabricMC/fabric#2355] opened 2022-06-23 13:53 UTC
```
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-object-builder-api-v1
    at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.mapping.reader.v2.MappingParseException: Error on line "    m    (Ldhq$a;Lgt;)V    b    method_
```
this is the error coming when i try to run my game 
is this issues is already reported then please ignore it

**Comment by Juuxel** [comment] 2022-06-23 14:28
Duplicate of #2354.

**Closed as completed by Juuxel** 2022-06-23 14:28 UTC
Labels: resolution: duplicate
