### ISSUE TITLE
When I try to join a world with Fabric API, the game crashes.

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1505] opened 2021-06-19 10:31 UTC
Minecraft Version: 1.17 Release
Fabric Loader Version: fabric-loader-0.11.6-1.17
Fabric API Version: fabric-api-0.35.2+1.17

When I try to join a world with Fabric API, the game crashes. It happens even when Fabric API is the only mod I have in the "mods" folder.
[crash-2021-06-19_12.29.37-client.txt](https://github.com/FabricMC/fabric/files/6680502/crash-2021-06-19_12.29.37-client.txt)

**Comment by iPotFast** [comment] 2021-06-19 13:21
Same thing here it says this 

Could not find required mod: hwg requires {geckolib3 @ [>=3.0.4]}

**Comment by iPotFast** [comment] 2021-06-19 13:32
I know whats the problem man some og the mods are not working try removing all of them then adding them 1 by 1 to see what works and what not

**Comment by liach** [comment] 2021-06-20 15:29
I recall seeing an exact same crash caused by the same indigo casting vanilla baked model to fabric baked model, but none of us here could find a way to replicate this issue.

**Comment by Technici4n** [comment] 2021-06-29 14:13
Duplicate of #1479

**Comment by switchsponge** [comment] 2021-07-09 03:53
To clarify, as I have been experiencing the same problem also and this has been flagged as duplicates so I won't make another report on this, is this problem caused by using some weird/cracked launcher or you can't suggest a fix as you can't replicate the problem?

**Comment by liach** [comment] 2021-07-09 16:09
Hmm, I don't think this one is quite launcher-related, as I cannot see what launcher is used in this case. How did you install your fabric api, just curious?

**Comment by switchsponge** [comment] 2021-07-09 16:21
From the link on the website... In the original report, if I read it correctly, they were using a cracked launcher and that someone commented (I think it was you, actually) that it probably has something to do with the launcher not parsing jsons properly or something and then the report was closed as cracked launchers are not supported.

**Comment by liach** [comment] 2021-07-09 16:23
If you can get this crash with multiple launchers or the vanilla launcher (and tell us the steps), then it more likely would be the problem with fabric loader or minecraft than the launchers.

These 2 issues have the same symptoms, but their causes may be different.

**Comment by Technici4n** [comment] 2021-07-09 16:25
Someone had the issue yesterday on discord as well (or the day before), and reinstalling fabric into the vanilla launcher fixed it. Maybe an issue with installer, such as a weird corner case like out of disk space, or antivirus, or idk what.

**Comment by liach** [comment] 2021-07-09 16:27
@switchsponge What's your case then? If you have tried a few launchers, then post all their crash reports and we can check. If you only have tried one, can't help much in that case.

**Comment by switchsponge** [comment] 2021-07-09 16:33
Unfortunately, I am using a cracked launcher (and yes I will buy the game eventually but I live in a country where $20 isn't cheap and spending that amount of money on a video game is absurd given the amount of other things $20 here can buy but anyway I digress) I was able to fix the problem by enabling some compatibility option in the launcher that disabled their skins system. So yeah, I was expecting it was a bug or something in the API but I guess it has just something to do with compatibility.

**Comment by modmuss50** [comment] 2021-07-09 16:34
Cracked launchers are not supported. I believe this issue is mostly seen on cracked launchers. That user had a corrupt if im not mistaken.

**Closed as completed by modmuss50** 2021-07-09 16:34 UTC
Labels: question
