### ISSUE TITLE
Incompatible mod set! for fabric 20w14infinite

### ISSUE THREAD

**Issue by boomoliver** [FabricMC/fabric#2819] opened 2023-01-03 00:56 UTC
Im using fabric-api-0.5.7+build.2-20w14infinite because I can't find another one to try. I really don't understand what I need to do here, I installed both fabric and fabric api to 20w14infinite, I disabled all mods but still it doesn't work. Help please! 
![6642](https://user-images.githubusercontent.com/121836765/210288148-9fb91229-1b88-4e5d-aff4-d4efca538f92.png)

**Comment by Juuxel** [comment] 2023-01-03 08:58
Duplicate of #2546.

**Closed as not planned by Juuxel** 2023-01-03 08:58 UTC
Labels: resolution: duplicate
