### ISSUE TITLE
Artifice 1.18.1 not compatible with the latest Fabric APIs? 

### ISSUE THREAD

**Issue by JackDainzh** [FabricMC/fabric#1933] opened 2021-12-24 06:23 UTC
So I started updating the artifice mod used for dynamically programmed resource files, used by such mods as previously by Adorn and now by Extra Pieces. It appears so that dynamic loot tables and crafting, basically stonecutting too and all that custom stuff is not working anymore. The mod is initialized, it runs, the models of the blocks are there, but the mandatory parts of looting and crafting are not. I did not change the source code of the mod itself, just changed the mappings and made build.gradle easier to use. If someone would like to help me, I could post the source code here, until now, I genuinely sick your help..

**Comment by warjort** [comment] 2021-12-24 15:48
Its hard to say what is going on with so little information.

I can guess that since the models (client/assets side) are working but the loot tables and recipes (server/data side) is not then you need to find out what is (not) happening with the data packs.

At first glance, this seems to being done here:
https://github.com/natanfudge/artifice/blob/1.17/src/main/java/com/swordglowsblue/artifice/mixin/MixinResourcePackManager.java
with some heuristics based on whether it is in dedicated server mode or the ClientBuiltinResourcePackProvider is present.

My second guess, would be something related to the class/api breaking changes mentioned here:
https://github.com/FabricMC/fabric/issues/1818
This modification done in the name of performance is not very compatible with other mods doing non-trivial resource loading changes.

**Comment by JackDainzh** [comment] 2021-12-24 20:01
Sorry if I would say such as silly thing, but what would be my actions here? I am quite new into all of this, and I need a guideline I could try to follow in order for me to do anything. If it's a bug at all, what can I do to fix it? Thanks in advance!

**Comment by warjort** [comment] 2021-12-24 20:15
You should start with creating your issue in the correct project:
https://github.com/natanfudge/artifice/issues

You should include as much information as possible, e.g.
* versions of everything (minecraft, mods, fabric, os, java, etc.)
* logs (logs/latest.log)
* an example that is as simple as possible (no complicated setup) to reproduce the problem for the person trying to analyse/fix it

**Comment by oliviathevampire** [comment] 2021-12-24 20:45
Hi! Me and my team currently have mostly taken over the development of Artifice! We'll be making a new version asap! @warjort and @JackDainzh

**Comment by JackDainzh** [comment] 2021-12-24 21:00
NO WAY! this is so great to hear @oliviathevampire! @warjort Yea... that was the issue, the repository was archived so I decided to update is myself, didn't end well as you can see.. )

**Comment by modmuss50** [comment] 2021-12-24 21:02
Am I ok to close this? I fail to see how this is a fabric issue unless im missing something?

**Comment by JackDainzh** [comment] 2021-12-24 21:04
@modmuss50 Sorry for disturbing, I think I misjudged some things about what could be done and what not. Will try to figure the rest out, Thanks.

**Closed as completed** 2021-12-24 23:40 UTC
